os:
  - linux
language: node_js
node_js:
  - "8.10.0"
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=chromium-browser
  # Install Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn -v
install:
  - yarn install

before_script:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
script:
  - yarn test
  - yarn build

notifications:
  email: true
